POST http://localhost:3005/login
Content-Type: application/json

{
    "memberid":"admin",
    "password":"123"
}

###
POST http://localhost:3005/register
Content-Type: application/json

{
    "memberid":"adm",
    "password":"123"
}

###
POST http://localhost:3005/newrecord
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJpZCI6ImFkbWluIiwiaWF0IjoxNjQ2NTU0NTI3fQ.cPrBUnud8ftqg9zLWiLv0Eonb-SSeIvoVJ_8X2rwApc
Content-Type: application/json

{
    "memberid":"admin",
    "name":"sai",
    "date":"2022-02-16",
    "mobileNo":"1234",
    "BP":"12",
    "FBS":"123",
    "PPBS":"34",
    "RBS":"54",
    "HbA1C":"45",
    "Urea":"67",
    "Creatinine":"34",
    "Complains":"no",
    "OtherSignificantNotes":""
}

###
GET http://localhost:3005/showrecord
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJpZCI6ImFkbWluIiwiaWF0IjoxNjQ2NTU0NTI3fQ.cPrBUnud8ftqg9zLWiLv0Eonb-SSeIvoVJ_8X2rwApc